from __future__ import annotations

import json
import math
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import mean_absolute_error, mean_squared_error
from torch import nn
from torch.utils.data import DataLoader, TensorDataset


@dataclass(frozen=True)
class PhaseFiveConfig:
    """Configuration for the PatchTST-style multivariate forecasting benchmark."""

    input_data_path: Path = Path("Assignment1/outputs/phase1/modeling_data.csv")
    phase3_metadata_path: Path = Path("Assignment1/outputs/phase3/model_metadata.json")
    output_dir: Path = Path("Assignment1/outputs/phase5")
    target_column: str = "nasdaq log_return"
    holdout_size: int = 252
    validation_size: int = 252
    lookback_window: int = 60
    patch_length: int = 10
    patch_stride: int = 5
    d_model: int = 32
    num_heads: int = 4
    num_layers: int = 2
    feedforward_dim: int = 64
    dropout: float = 0.10
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    batch_size: int = 64
    max_epochs: int = 40
    early_stopping_patience: int = 8
    gradient_clip_norm: float = 1.0
    random_seed: int = 7
    device: str = "cpu"


@dataclass(frozen=True)
class PhaseFiveArtifacts:
    """Outputs generated by the deep-learning forecasting pipeline."""

    design_data: pd.DataFrame
    training_history: pd.DataFrame
    validation_predictions: pd.DataFrame
    test_predictions: pd.DataFrame
    feature_schema: pd.DataFrame
    model_metadata: dict[str, Any]
    model_state_dict: dict[str, torch.Tensor]

    def summary(self) -> str:
        metrics = self.model_metadata["evaluation_metrics"]
        return (
            f"Target: {self.model_metadata['target_column']} | "
            f"Architecture: {self.model_metadata['architecture']} | "
            f"Train/Val/Test windows: {self.model_metadata['train_windows']} / "
            f"{self.model_metadata['validation_windows']} / {self.model_metadata['test_windows']} | "
            f"Test RMSE: {metrics['rmse']:.6f} | "
            f"Test hit rate: {metrics['directional_accuracy']:.4f}"
        )


class PatchTSTForecaster(nn.Module):
    """
    PatchTST-style encoder for one-step-ahead forecasting.

    The key design choice is patching the lookback window so the model sees short
    local segments instead of treating every single day as a separate token. This
    reduces sequence length, gives each token a local temporal meaning, and keeps
    the model small enough to train reproducibly on CPU for this assignment.
    """

    def __init__(
        self,
        num_channels: int,
        lookback_window: int,
        patch_length: int,
        patch_stride: int,
        d_model: int,
        num_heads: int,
        num_layers: int,
        feedforward_dim: int,
        dropout: float,
    ) -> None:
        super().__init__()
        if lookback_window < patch_length:
            raise ValueError("Patch length cannot exceed the lookback window.")

        self.num_channels = num_channels
        self.lookback_window = lookback_window
        self.patch_length = patch_length
        self.patch_stride = patch_stride
        self.num_patches = 1 + (lookback_window - patch_length) // patch_stride

        self.patch_embedding = nn.Linear(patch_length, d_model)
        self.position_embedding = nn.Parameter(torch.zeros(1, 1, self.num_patches, d_model))

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=num_heads,
            dim_feedforward=feedforward_dim,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.channel_norm = nn.LayerNorm(d_model)
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(num_channels * d_model, feedforward_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(feedforward_dim, 1),
        )

        nn.init.normal_(self.position_embedding, mean=0.0, std=0.02)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        # Expected input shape: [batch, lookback_window, num_channels].
        series = inputs.transpose(1, 2)
        patches = series.unfold(dimension=2, size=self.patch_length, step=self.patch_stride)
        tokens = self.patch_embedding(patches) + self.position_embedding

        batch_size, num_channels, num_patches, d_model = tokens.shape
        encoded = self.encoder(tokens.reshape(batch_size * num_channels, num_patches, d_model))
        pooled = self.channel_norm(encoded.mean(dim=1)).reshape(batch_size, num_channels, d_model)
        forecast = self.head(pooled).squeeze(-1)
        return forecast


class PatchTSTDeepForecaster:
    """Prepare the multivariate dataset, train the model, and score the holdout forecast."""

    def __init__(self, config: PhaseFiveConfig) -> None:
        self.config = config

    def run(self) -> PhaseFiveArtifacts:
        self._set_random_seed()

        base_frame = pd.read_csv(self.config.input_data_path, parse_dates=["date"]).sort_values("date").reset_index(drop=True)
        design_data, feature_schema = self._build_design_matrix(base_frame)

        (
            feature_matrix,
            target_vector,
            target_dates,
            split_summary,
            scaling_stats,
        ) = self._prepare_scaled_arrays(design_data)

        datasets = self._build_window_datasets(feature_matrix, target_vector, target_dates, split_summary)

        model = PatchTSTForecaster(
            num_channels=feature_matrix.shape[1],
            lookback_window=self.config.lookback_window,
            patch_length=self.config.patch_length,
            patch_stride=self.config.patch_stride,
            d_model=self.config.d_model,
            num_heads=self.config.num_heads,
            num_layers=self.config.num_layers,
            feedforward_dim=self.config.feedforward_dim,
            dropout=self.config.dropout,
        ).to(self.config.device)

        training_history, best_state, best_epoch = self._fit_model(model, datasets)
        model.load_state_dict(best_state)

        validation_predictions = self._predict_split(model, datasets["validation"])
        test_predictions = self._predict_split(model, datasets["test"])
        phase3_benchmark = self._load_phase3_benchmark()
        model_metadata = self._build_metadata(
            design_data=design_data,
            split_summary=split_summary,
            scaling_stats=scaling_stats,
            training_history=training_history,
            validation_predictions=validation_predictions,
            test_predictions=test_predictions,
            feature_schema=feature_schema,
            best_epoch=best_epoch,
            phase3_benchmark=phase3_benchmark,
        )

        return PhaseFiveArtifacts(
            design_data=design_data,
            training_history=training_history,
            validation_predictions=validation_predictions,
            test_predictions=test_predictions,
            feature_schema=feature_schema,
            model_metadata=model_metadata,
            model_state_dict=best_state,
        )

    def _set_random_seed(self) -> None:
        random.seed(self.config.random_seed)
        np.random.seed(self.config.random_seed)
        torch.manual_seed(self.config.random_seed)
        torch.set_num_threads(max(1, min(4, os.cpu_count() or 4)))

    def _build_design_matrix(self, frame: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
        assets = [column.removesuffix(" log_return") for column in frame.columns if column.endswith(" log_return")]
        design = pd.DataFrame({"date": frame["date"], "target": frame[self.config.target_column]})
        schema_rows: list[dict[str, str]] = []

        for asset in assets:
            for suffix, category, description in [
                ("log_return", "returns", "Daily continuously compounded return."),
                ("rsi_14", "momentum", "14-day relative strength index."),
                ("macd_hist", "trend_momentum", "MACD histogram: trend strength after signal subtraction."),
                ("bb_zscore", "relative_price", "Distance from rolling Bollinger middle band in standard-deviation units."),
            ]:
                column_name = f"{asset} {suffix}"
                feature_name = f"{asset}_{suffix}"
                design[feature_name] = frame[column_name].shift(1)
                schema_rows.append(
                    {
                        "feature": feature_name,
                        "category": category,
                        "source_column": column_name,
                        "description": description,
                    }
                )

        for fx_column in ("eur_usd", "usd_chf"):
            feature_name = f"{fx_column}_ret_l1"
            design[feature_name] = np.log(frame[fx_column] / frame[fx_column].shift(1)).shift(1)
            schema_rows.append(
                {
                    "feature": feature_name,
                    "category": "fx_return",
                    "source_column": fx_column,
                    "description": "Lagged one-day log return of the exchange rate.",
                }
            )

        design["gdp_growth_l1"] = np.log(frame["GDP"] / frame["GDP"].shift(1)).shift(1)
        design["cpi_inflation_l1"] = np.log(frame["CPI"] / frame["CPI"].shift(1)).shift(1)
        design["rate_change_l1"] = frame["us_rates_%"].diff().shift(1)

        schema_rows.extend(
            [
                {
                    "feature": "gdp_growth_l1",
                    "category": "macro_change",
                    "source_column": "GDP",
                    "description": "Lagged log difference in GDP, used as a low-frequency growth proxy.",
                },
                {
                    "feature": "cpi_inflation_l1",
                    "category": "macro_change",
                    "source_column": "CPI",
                    "description": "Lagged log difference in CPI, used as an inflation proxy.",
                },
                {
                    "feature": "rate_change_l1",
                    "category": "macro_change",
                    "source_column": "us_rates_%",
                    "description": "Lagged first difference in the policy rate level.",
                },
            ]
        )

        design = design.dropna().reset_index(drop=True)
        feature_schema = pd.DataFrame(schema_rows)
        return design, feature_schema

    def _prepare_scaled_arrays(
        self,
        design_data: pd.DataFrame,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any], dict[str, dict[str, float]]]:
        if len(design_data) <= self.config.lookback_window + self.config.validation_size + self.config.holdout_size:
            raise ValueError("Not enough observations to create time windows with the configured splits.")

        feature_columns = [column for column in design_data.columns if column not in {"date", "target"}]
        feature_values = design_data[feature_columns].to_numpy(dtype=np.float32)
        target_values = design_data["target"].to_numpy(dtype=np.float32)
        target_dates = design_data["date"].to_numpy()

        test_start = len(design_data) - self.config.holdout_size
        validation_start = test_start - self.config.validation_size
        train_end = validation_start

        feature_mean = feature_values[:train_end].mean(axis=0)
        feature_std = feature_values[:train_end].std(axis=0)
        feature_std = np.where(feature_std == 0.0, 1.0, feature_std)

        target_mean = float(target_values[:train_end].mean())
        target_std = float(target_values[:train_end].std())
        target_std = 1.0 if target_std == 0.0 else target_std

        scaled_features = (feature_values - feature_mean) / feature_std
        scaled_target = (target_values - target_mean) / target_std

        split_summary = {
            "train_target_start": self.config.lookback_window,
            "train_target_end": train_end,
            "validation_target_start": validation_start,
            "validation_target_end": test_start,
            "test_target_start": test_start,
            "test_target_end": len(design_data),
            "feature_columns": feature_columns,
        }
        scaling_stats = {
            "feature_mean": {column: float(value) for column, value in zip(feature_columns, feature_mean, strict=True)},
            "feature_std": {column: float(value) for column, value in zip(feature_columns, feature_std, strict=True)},
            "target_mean": {"target": target_mean},
            "target_std": {"target": target_std},
        }
        return scaled_features, scaled_target, target_dates, split_summary, scaling_stats

    def _build_window_datasets(
        self,
        feature_matrix: np.ndarray,
        target_vector: np.ndarray,
        target_dates: np.ndarray,
        split_summary: dict[str, Any],
    ) -> dict[str, dict[str, Any]]:
        datasets: dict[str, dict[str, Any]] = {}
        for split_name, start_key, end_key in [
            ("train", "train_target_start", "train_target_end"),
            ("validation", "validation_target_start", "validation_target_end"),
            ("test", "test_target_start", "test_target_end"),
        ]:
            start = int(split_summary[start_key])
            end = int(split_summary[end_key])
            target_indices = np.arange(start, end, dtype=int)
            inputs, targets, dates = self._build_windows(feature_matrix, target_vector, target_dates, target_indices)
            tensor_dataset = TensorDataset(
                torch.tensor(inputs, dtype=torch.float32),
                torch.tensor(targets, dtype=torch.float32),
            )
            datasets[split_name] = {
                "dataset": tensor_dataset,
                "inputs": inputs,
                "targets": targets,
                "dates": pd.to_datetime(dates),
            }
        return datasets

    def _build_windows(
        self,
        feature_matrix: np.ndarray,
        target_vector: np.ndarray,
        target_dates: np.ndarray,
        target_indices: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        windows = np.stack(
            [feature_matrix[index - self.config.lookback_window : index] for index in target_indices],
            axis=0,
        )
        targets = target_vector[target_indices]
        dates = target_dates[target_indices]
        return windows.astype(np.float32), targets.astype(np.float32), dates

    def _fit_model(
        self,
        model: PatchTSTForecaster,
        datasets: dict[str, dict[str, Any]],
    ) -> tuple[pd.DataFrame, dict[str, torch.Tensor], int]:
        train_loader = DataLoader(datasets["train"]["dataset"], batch_size=self.config.batch_size, shuffle=True)
        validation_loader = DataLoader(datasets["validation"]["dataset"], batch_size=self.config.batch_size, shuffle=False)

        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=self.config.learning_rate,
            weight_decay=self.config.weight_decay,
        )
        loss_fn = nn.MSELoss()

        best_state: dict[str, torch.Tensor] | None = None
        best_validation_loss = math.inf
        best_epoch = -1
        patience_counter = 0
        history_rows: list[dict[str, float | int]] = []

        for epoch in range(1, self.config.max_epochs + 1):
            model.train()
            train_losses: list[float] = []
            for features, target in train_loader:
                features = features.to(self.config.device)
                target = target.to(self.config.device)

                optimizer.zero_grad()
                prediction = model(features)
                loss = loss_fn(prediction, target)
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), max_norm=self.config.gradient_clip_norm)
                optimizer.step()
                train_losses.append(float(loss.item()))

            model.eval()
            validation_losses: list[float] = []
            with torch.no_grad():
                for features, target in validation_loader:
                    features = features.to(self.config.device)
                    target = target.to(self.config.device)
                    prediction = model(features)
                    validation_losses.append(float(loss_fn(prediction, target).item()))

            train_loss = float(np.mean(train_losses))
            validation_loss = float(np.mean(validation_losses))
            history_rows.append(
                {
                    "epoch": epoch,
                    "train_loss": train_loss,
                    "validation_loss": validation_loss,
                    "train_rmse": math.sqrt(train_loss),
                    "validation_rmse": math.sqrt(validation_loss),
                }
            )

            if validation_loss < best_validation_loss:
                best_validation_loss = validation_loss
                best_epoch = epoch
                best_state = {name: value.detach().cpu().clone() for name, value in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= self.config.early_stopping_patience:
                    break

        if best_state is None:
            raise RuntimeError("Training completed without producing a valid model state.")

        return pd.DataFrame(history_rows), best_state, best_epoch

    def _predict_split(self, model: PatchTSTForecaster, split_data: dict[str, Any]) -> pd.DataFrame:
        model.eval()
        inputs = torch.tensor(split_data["inputs"], dtype=torch.float32, device=self.config.device)

        with torch.no_grad():
            scaled_predictions = model(inputs).detach().cpu().numpy()

        predictions = pd.DataFrame(
            {
                "date": split_data["dates"],
                "target_scaled": split_data["targets"],
                "prediction_scaled": scaled_predictions,
            }
        )
        predictions["actual"] = predictions["target_scaled"]
        predictions["forecast"] = predictions["prediction_scaled"]
        return predictions

    def _load_phase3_benchmark(self) -> dict[str, float] | None:
        if not self.config.phase3_metadata_path.exists():
            return None
        with open(self.config.phase3_metadata_path, "r", encoding="utf-8") as handle:
            metadata = json.load(handle)
        metrics = metadata.get("evaluation_metrics", {})
        return {
            "rmse": float(metrics.get("rmse", np.nan)),
            "mae": float(metrics.get("mae", np.nan)),
            "directional_accuracy": float(metrics.get("directional_accuracy", np.nan)),
        }

    def _build_metadata(
        self,
        design_data: pd.DataFrame,
        split_summary: dict[str, Any],
        scaling_stats: dict[str, dict[str, float]],
        training_history: pd.DataFrame,
        validation_predictions: pd.DataFrame,
        test_predictions: pd.DataFrame,
        feature_schema: pd.DataFrame,
        best_epoch: int,
        phase3_benchmark: dict[str, float] | None,
    ) -> dict[str, Any]:
        target_mean = scaling_stats["target_mean"]["target"]
        target_std = scaling_stats["target_std"]["target"]

        for frame in (validation_predictions, test_predictions):
            frame["actual"] = frame["target_scaled"] * target_std + target_mean
            frame["forecast"] = frame["prediction_scaled"] * target_std + target_mean
            frame["forecast_error"] = frame["actual"] - frame["forecast"]
            frame["predicted_direction"] = np.sign(frame["forecast"])
            frame["actual_direction"] = np.sign(frame["actual"])
            frame["direction_correct"] = frame["predicted_direction"] == frame["actual_direction"]

        test_metrics = {
            "rmse": float(np.sqrt(mean_squared_error(test_predictions["actual"], test_predictions["forecast"]))),
            "mae": float(mean_absolute_error(test_predictions["actual"], test_predictions["forecast"])),
            "directional_accuracy": float(test_predictions["direction_correct"].mean()),
            "mean_forecast_error": float(test_predictions["forecast_error"].mean()),
            "forecast_actual_correlation": float(
                np.corrcoef(test_predictions["actual"], test_predictions["forecast"])[0, 1]
            ),
        }
        validation_metrics = {
            "rmse": float(np.sqrt(mean_squared_error(validation_predictions["actual"], validation_predictions["forecast"]))),
            "mae": float(mean_absolute_error(validation_predictions["actual"], validation_predictions["forecast"])),
            "directional_accuracy": float(validation_predictions["direction_correct"].mean()),
        }

        return {
            "target_column": self.config.target_column,
            "architecture": "PatchTST-style transformer encoder",
            "feature_count": int(len(split_summary["feature_columns"])),
            "lookback_window": self.config.lookback_window,
            "patch_length": self.config.patch_length,
            "patch_stride": self.config.patch_stride,
            "num_patches": 1 + (self.config.lookback_window - self.config.patch_length) // self.config.patch_stride,
            "d_model": self.config.d_model,
            "num_heads": self.config.num_heads,
            "num_layers": self.config.num_layers,
            "dropout": self.config.dropout,
            "learning_rate": self.config.learning_rate,
            "weight_decay": self.config.weight_decay,
            "batch_size": self.config.batch_size,
            "best_epoch": int(best_epoch),
            "max_epochs": self.config.max_epochs,
            "train_rows": int(len(design_data)),
            "train_windows": int(split_summary["train_target_end"] - split_summary["train_target_start"]),
            "validation_windows": int(split_summary["validation_target_end"] - split_summary["validation_target_start"]),
            "test_windows": int(split_summary["test_target_end"] - split_summary["test_target_start"]),
            "train_start": str(design_data["date"].iloc[0].date()),
            "train_end": str(design_data["date"].iloc[split_summary["train_target_end"] - 1].date()),
            "validation_start": str(design_data["date"].iloc[split_summary["validation_target_start"]].date()),
            "validation_end": str(design_data["date"].iloc[split_summary["validation_target_end"] - 1].date()),
            "test_start": str(design_data["date"].iloc[split_summary["test_target_start"]].date()),
            "test_end": str(design_data["date"].iloc[split_summary["test_target_end"] - 1].date()),
            "feature_scaling": scaling_stats,
            "feature_categories": feature_schema["category"].value_counts().sort_index().to_dict(),
            "evaluation_metrics": test_metrics,
            "validation_metrics": validation_metrics,
            "phase3_benchmark": phase3_benchmark,
            "training_history_tail": training_history.tail(5).to_dict(orient="records"),
        }


class PhaseFivePipeline:
    """Persist Phase 5 deep-learning outputs and summaries."""

    def __init__(self, config: PhaseFiveConfig | None = None) -> None:
        self.config = config or PhaseFiveConfig()
        self.forecaster = PatchTSTDeepForecaster(self.config)

    def run(self, save_outputs: bool = True) -> PhaseFiveArtifacts:
        artifacts = self.forecaster.run()
        if save_outputs:
            self._write_outputs(artifacts)
        return artifacts

    def _write_outputs(self, artifacts: PhaseFiveArtifacts) -> None:
        self.config.output_dir.mkdir(parents=True, exist_ok=True)
        artifacts.design_data.to_csv(self.config.output_dir / "phase5_design_data.csv", index=False)
        artifacts.training_history.to_csv(self.config.output_dir / "training_history.csv", index=False)
        artifacts.validation_predictions.to_csv(self.config.output_dir / "validation_predictions.csv", index=False)
        artifacts.test_predictions.to_csv(self.config.output_dir / "test_predictions.csv", index=False)
        artifacts.feature_schema.to_csv(self.config.output_dir / "feature_schema.csv", index=False)
        torch.save(artifacts.model_state_dict, self.config.output_dir / "patchtst_state_dict.pt")
        with open(self.config.output_dir / "model_metadata.json", "w", encoding="utf-8") as handle:
            json.dump(artifacts.model_metadata, handle, indent=2)
