from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from pmdarima import auto_arima
from scipy import stats
from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.stats.stattools import jarque_bera
from statsmodels.tsa.statespace.sarimax import SARIMAX


@dataclass(frozen=True)
class PhaseThreeConfig:
    """Configuration for the classical SARIMAX benchmark."""

    input_data_path: Path = Path("Assignment1/outputs/phase1/modeling_data.csv")
    output_dir: Path = Path("Assignment1/outputs/phase3")
    target_column: str = "nasdaq log_return"
    holdout_size: int = 252
    exogenous_return_assets: tuple[str, ...] = ("sp500", "gold", "oil")
    exogenous_fx_columns: tuple[str, ...] = ("eur_usd", "usd_chf")
    auto_arima_max_p: int = 5
    auto_arima_max_q: int = 5
    auto_arima_max_d: int = 1
    seasonal: bool = False
    seasonal_period: int = 5
    ljung_box_lags: tuple[int, ...] = (5, 10, 20)
    confidence_alpha: float = 0.05


@dataclass(frozen=True)
class PhaseThreeArtifacts:
    """Outputs generated by the classical baseline pipeline."""

    design_data: pd.DataFrame
    train_results: pd.DataFrame
    test_forecasts: pd.DataFrame
    coefficient_summary: pd.DataFrame
    residual_diagnostics: pd.DataFrame
    qq_plot_data: pd.DataFrame
    model_metadata: dict[str, Any]

    def summary(self) -> str:
        metrics = self.model_metadata["evaluation_metrics"]
        order = tuple(self.model_metadata["order"])
        seasonal_order = tuple(self.model_metadata["seasonal_order"])
        return (
            f"Target: {self.model_metadata['target_column']} | "
            f"Order: {order} | Seasonal order: {seasonal_order} | "
            f"Train rows: {self.model_metadata['train_rows']} | "
            f"Test rows: {self.model_metadata['test_rows']} | "
            f"Test RMSE: {metrics['rmse']:.6f} | "
            f"Test hit rate: {metrics['directional_accuracy']:.4f}"
        )


class SarimaxBaselineBuilder:
    """Build a leakage-aware exogenous design and fit the classical benchmark."""

    def __init__(self, config: PhaseThreeConfig) -> None:
        self.config = config

    def run(self) -> PhaseThreeArtifacts:
        base_frame = pd.read_csv(self.config.input_data_path, parse_dates=["date"]).sort_values("date").reset_index(drop=True)
        design_data = self._build_design_matrix(base_frame)
        train_data, test_data = self._split_train_test(design_data)

        exogenous_columns = [column for column in design_data.columns if column not in {"date", "target"}]
        x_train, x_test, scaling_stats = self._scale_exogenous(train_data[exogenous_columns], test_data[exogenous_columns])
        y_train = train_data["target"]

        auto_model = auto_arima(
            y=y_train,
            X=x_train,
            seasonal=self.config.seasonal,
            m=self.config.seasonal_period if self.config.seasonal else 1,
            information_criterion="aic",
            stepwise=True,
            suppress_warnings=True,
            error_action="ignore",
            trace=False,
            max_p=self.config.auto_arima_max_p,
            max_q=self.config.auto_arima_max_q,
            max_d=self.config.auto_arima_max_d,
            start_p=0,
            start_q=0,
            d=None,
            with_intercept=True,
        )

        trend = "c" if getattr(auto_model, "with_intercept", True) else "n"
        sarimax_model = SARIMAX(
            endog=y_train,
            exog=x_train,
            order=auto_model.order,
            seasonal_order=auto_model.seasonal_order,
            trend=trend,
            enforce_stationarity=False,
            enforce_invertibility=False,
        )
        fitted_model = sarimax_model.fit(disp=False)

        train_results = self._build_train_results(train_data, fitted_model)
        test_forecasts = self._build_test_forecasts(test_data, x_test, fitted_model)
        coefficient_summary = self._build_coefficient_summary(fitted_model)
        residual_diagnostics = self._build_residual_diagnostics(train_results["residual"])
        qq_plot_data = self._build_qq_plot_data(train_results["residual"])
        model_metadata = self._build_metadata(
            design_data=design_data,
            train_data=train_data,
            test_data=test_data,
            fitted_model=fitted_model,
            auto_model=auto_model,
            exogenous_columns=exogenous_columns,
            scaling_stats=scaling_stats,
            test_forecasts=test_forecasts,
            residual_diagnostics=residual_diagnostics,
        )

        return PhaseThreeArtifacts(
            design_data=design_data,
            train_results=train_results,
            test_forecasts=test_forecasts,
            coefficient_summary=coefficient_summary,
            residual_diagnostics=residual_diagnostics,
            qq_plot_data=qq_plot_data,
            model_metadata=model_metadata,
        )

    def _build_design_matrix(self, frame: pd.DataFrame) -> pd.DataFrame:
        design = pd.DataFrame({"date": frame["date"], "target": frame[self.config.target_column]})

        for asset_name in self.config.exogenous_return_assets:
            design[f"{asset_name}_ret_l1"] = frame[f"{asset_name} log_return"].shift(1)

        for fx_column in self.config.exogenous_fx_columns:
            fx_return = np.log(frame[fx_column] / frame[fx_column].shift(1))
            design[f"{fx_column}_ret_l1"] = fx_return.shift(1)

        # Macro levels are differenced in transformed form so the exogenous block
        # reflects changes in the economic environment rather than raw non-stationary levels.
        design["gdp_growth_l1"] = np.log(frame["GDP"] / frame["GDP"].shift(1)).shift(1)
        design["cpi_inflation_l1"] = np.log(frame["CPI"] / frame["CPI"].shift(1)).shift(1)
        design["rate_change_l1"] = frame["us_rates_%"].diff().shift(1)

        return design.dropna().reset_index(drop=True)

    def _split_train_test(self, design_data: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
        if len(design_data) <= self.config.holdout_size:
            raise ValueError("Holdout size is too large for the available design matrix.")

        train_rows = len(design_data) - self.config.holdout_size
        train_data = design_data.iloc[:train_rows].reset_index(drop=True)
        test_data = design_data.iloc[train_rows:].reset_index(drop=True)
        return train_data, test_data

    @staticmethod
    def _scale_exogenous(
        x_train: pd.DataFrame,
        x_test: pd.DataFrame,
    ) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, dict[str, float]]]:
        means = x_train.mean()
        stds = x_train.std(ddof=0).replace(0.0, 1.0)
        scaled_train = (x_train - means) / stds
        scaled_test = (x_test - means) / stds
        scaling_stats = {
            "mean": {column: float(value) for column, value in means.items()},
            "std": {column: float(value) for column, value in stds.items()},
        }
        return scaled_train, scaled_test, scaling_stats

    @staticmethod
    def _build_train_results(train_data: pd.DataFrame, fitted_model) -> pd.DataFrame:
        fitted_values = fitted_model.fittedvalues
        residuals = train_data["target"] - fitted_values
        return pd.DataFrame(
            {
                "date": train_data["date"],
                "actual": train_data["target"],
                "fitted": fitted_values,
                "residual": residuals,
            }
        )

    def _build_test_forecasts(self, test_data: pd.DataFrame, x_test: pd.DataFrame, fitted_model) -> pd.DataFrame:
        forecast_result = fitted_model.get_forecast(steps=len(test_data), exog=x_test)
        forecast_frame = forecast_result.summary_frame(alpha=self.config.confidence_alpha)

        forecasts = pd.DataFrame(
            {
                "date": test_data["date"],
                "actual": test_data["target"],
                "forecast": forecast_frame["mean"].to_numpy(),
                "lower_ci": forecast_frame["mean_ci_lower"].to_numpy(),
                "upper_ci": forecast_frame["mean_ci_upper"].to_numpy(),
            }
        )
        forecasts["forecast_error"] = forecasts["actual"] - forecasts["forecast"]
        forecasts["predicted_direction"] = np.sign(forecasts["forecast"])
        forecasts["actual_direction"] = np.sign(forecasts["actual"])
        forecasts["direction_correct"] = forecasts["predicted_direction"] == forecasts["actual_direction"]
        return forecasts

    @staticmethod
    def _build_coefficient_summary(fitted_model) -> pd.DataFrame:
        confidence_intervals = fitted_model.conf_int()
        return pd.DataFrame(
            {
                "parameter": fitted_model.params.index,
                "coefficient": fitted_model.params.values,
                "std_error": fitted_model.bse.values,
                "z_score": fitted_model.zvalues.values,
                "p_value": fitted_model.pvalues.values,
                "ci_lower": confidence_intervals.iloc[:, 0].values,
                "ci_upper": confidence_intervals.iloc[:, 1].values,
            }
        )

    def _build_residual_diagnostics(self, residuals: pd.Series) -> pd.DataFrame:
        ljung_box = acorr_ljungbox(residuals, lags=list(self.config.ljung_box_lags), return_df=True).reset_index()
        ljung_box = ljung_box.rename(columns={"index": "lag", "lb_stat": "ljung_box_stat", "lb_pvalue": "ljung_box_pvalue"})

        jb_stat, jb_pvalue, skewness, kurtosis = jarque_bera(residuals)
        jarque_row = pd.DataFrame(
            {
                "lag": ["jarque_bera"],
                "ljung_box_stat": [float(jb_stat)],
                "ljung_box_pvalue": [float(jb_pvalue)],
                "skewness": [float(skewness)],
                "kurtosis": [float(kurtosis)],
            }
        )

        ljung_box["skewness"] = np.nan
        ljung_box["kurtosis"] = np.nan
        return pd.concat([ljung_box, jarque_row], ignore_index=True)

    @staticmethod
    def _build_qq_plot_data(residuals: pd.Series) -> pd.DataFrame:
        theoretical_quantiles, ordered_residuals = stats.probplot(residuals, dist="norm", fit=False)
        qq_frame = pd.DataFrame(
            {
                "theoretical_quantile": theoretical_quantiles,
                "sample_quantile": ordered_residuals,
            }
        )
        regression = stats.linregress(qq_frame["theoretical_quantile"], qq_frame["sample_quantile"])
        qq_frame["reference_line"] = regression.intercept + regression.slope * qq_frame["theoretical_quantile"]
        return qq_frame

    def _build_metadata(
        self,
        design_data: pd.DataFrame,
        train_data: pd.DataFrame,
        test_data: pd.DataFrame,
        fitted_model,
        auto_model,
        exogenous_columns: list[str],
        scaling_stats: dict[str, dict[str, float]],
        test_forecasts: pd.DataFrame,
        residual_diagnostics: pd.DataFrame,
    ) -> dict[str, Any]:
        rmse = float(np.sqrt(mean_squared_error(test_forecasts["actual"], test_forecasts["forecast"])))
        mae = float(mean_absolute_error(test_forecasts["actual"], test_forecasts["forecast"]))
        directional_accuracy = float(test_forecasts["direction_correct"].mean())
        mean_forecast_error = float(test_forecasts["forecast_error"].mean())

        ljung_box_rows = residual_diagnostics[residual_diagnostics["lag"] != "jarque_bera"].copy()
        ljung_box_summary = {
            str(int(row["lag"])): {
                "statistic": float(row["ljung_box_stat"]),
                "p_value": float(row["ljung_box_pvalue"]),
            }
            for _, row in ljung_box_rows.iterrows()
        }
        jb_row = residual_diagnostics.loc[residual_diagnostics["lag"] == "jarque_bera"].iloc[0]

        return {
            "target_column": self.config.target_column,
            "order": list(auto_model.order),
            "seasonal_order": list(auto_model.seasonal_order),
            "aic_auto_arima": float(auto_model.aic()),
            "aic_sarimax": float(fitted_model.aic),
            "bic_sarimax": float(fitted_model.bic),
            "trend": fitted_model.model.trend,
            "train_rows": int(len(train_data)),
            "test_rows": int(len(test_data)),
            "design_rows": int(len(design_data)),
            "train_start": str(train_data["date"].min().date()),
            "train_end": str(train_data["date"].max().date()),
            "test_start": str(test_data["date"].min().date()),
            "test_end": str(test_data["date"].max().date()),
            "exogenous_columns": exogenous_columns,
            "scaling_stats": scaling_stats,
            "evaluation_metrics": {
                "rmse": rmse,
                "mae": mae,
                "directional_accuracy": directional_accuracy,
                "mean_forecast_error": mean_forecast_error,
            },
            "ljung_box": ljung_box_summary,
            "jarque_bera": {
                "statistic": float(jb_row["ljung_box_stat"]),
                "p_value": float(jb_row["ljung_box_pvalue"]),
                "skewness": float(jb_row["skewness"]),
                "kurtosis": float(jb_row["kurtosis"]),
            },
        }


class PhaseThreePipeline:
    """Orchestrate fitting, diagnostics, and persistence for the classical benchmark."""

    def __init__(self, config: PhaseThreeConfig | None = None) -> None:
        self.config = config or PhaseThreeConfig()
        self.builder = SarimaxBaselineBuilder(self.config)

    def run(self, save_outputs: bool = True) -> PhaseThreeArtifacts:
        artifacts = self.builder.run()
        if save_outputs:
            self._save_outputs(artifacts)
        return artifacts

    def _save_outputs(self, artifacts: PhaseThreeArtifacts) -> None:
        self.config.output_dir.mkdir(parents=True, exist_ok=True)
        artifacts.design_data.to_csv(self.config.output_dir / "phase3_design_data.csv", index=False)
        artifacts.train_results.to_csv(self.config.output_dir / "train_fitted.csv", index=False)
        artifacts.test_forecasts.to_csv(self.config.output_dir / "test_forecasts.csv", index=False)
        artifacts.coefficient_summary.to_csv(self.config.output_dir / "coefficient_summary.csv", index=False)
        artifacts.residual_diagnostics.to_csv(self.config.output_dir / "residual_diagnostics.csv", index=False)
        artifacts.qq_plot_data.to_csv(self.config.output_dir / "qq_plot_data.csv", index=False)
        with open(self.config.output_dir / "model_metadata.json", "w", encoding="utf-8") as handle:
            json.dump(artifacts.model_metadata, handle, indent=2)
